apiVersion: v1
kind: Service
metadata:
  name: collector
  labels:
    web-trans: https
    nrpc-trans: quic
    grpc-trans: grpc
spec:
  selector:
    app.kubernetes.io/name: MyApp
  ports:
    - name: grpc
      protocol: TCP
      port: 4317
    - name: nrpc
      protocol: UDP
      port: 443
