receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317
      http:
        endpoint: 0.0.0.0:4318

processors:
  batch:
  batch/test:

exporters:
  otlp:
    endpoint: otelcol:4317
  otlp/2:
    endpoint: otelcol2:4317
  # Data sources: traces, metrics, logs
  file:
    path: ./filename.json


extensions:
  health_check:
  pprof:
  zpages:

service:
#  extensions: [health_check, pprof, zpages]
  pipelines:
    traces:
      receivers: [otlp]
      processors: []
      exporters: [file]
#    traces/2:
#      receivers: [otlp/2]
#      processors: [batch/test]
#      exporters: [otlp/2]
    metrics:
      receivers: [otlp]
      processors: []
      exporters: [file]
    logs:
      receivers: [otlp]
      processors: []
      exporters: [file]
